<?php 

function ORLounge_menu(){
  $items['join/%/group'] = array(
     'page callback' => 'drupal_get_form',
     'page arguments'=>array('join_group_form'),
     'access callback' =>'access_login_user',
     'file'=>'group.inc',
  );
  $items['add_new_comment'] = array(
     'page callback' => 'add_new_comment',
     'access callback' =>true,
  );
   $items['create/%/group'] = array(
     'page callback' => 'drupal_get_form',
     'page arguments'=>array('create_group_form'),
     'access callback' =>'access_login_user',
     'file'=>'group.inc',
  );
  
   $items['welcome'] = array(
     'page callback'=>'registration_welcome',
     'access arguments' => array('access content'),	
    );


  return $items;
}

function access_login_user(){
  global $user;  
   if($user->uid==0){
     return false;
   }else if($user->name != arg(1)){
      return false;
   }else{
      return true;
   }
}
function ORLounge_block_info() {

  $blocks['welcome'] = array(
    'info' => t('Welcome to Orlounge'),
    'region' => -1,
    'status' => TRUE,
  );
  $blocks['join'] = array(
    'info' => t('Join ORLounge to'),
    'region' => -1,
    'status' => TRUE,
  );
  $blocks['home_faq'] = array(
    'info' => t('Home FAQ'),
    'region' => -1,
    'status' => TRUE,
  );
  $blocks['home_register_form'] = array(
    'info' => t('Register form block'),
    'region' => -1,
    'status' => TRUE,
  );

  $blocks['group_list'] = array(
    'info' => t('Group List'),
    'region' => -1,
    'status' => TRUE,
  );

  return $blocks;

}

function ORLounge_block_view($delta='') {
   $block = array();
  switch($delta) {
    case 'welcome':
      $block['subject'] = 'Welcome to Orlounge';
      $block['content'] = block_welcome_content();
      break;
    case 'join':
      $block['subject'] = 'Join ORLounge to';
      $block['content'] = block_join_content();
      break;
    case 'home_faq':
      $block['content'] = block_home_faq_content();
      break;
    case 'home_register_form':
      $block['subject'] = 'Join for free';
      $block['content'] = drupal_get_form('block_register_form');
      break;
    case 'group_list':
      $block['subject'] = 'Group List';
      $block['content'] =  group_list_form();
      break;
   }
   return $block;
}

function block_welcome_content(){
   $output = t('ORLounge is a community site for operating rooms. Doctors and nurses working in an operating room can create their own private Lounge sites and share their professional activities.');
  
 return $output; 
}
function block_join_content(){

   $output = '<div class="dt-sc-ico-content  type3"><div class="icon"> <span class="fa fa-hospital-o"><img src="/sites/all/themes/orlounge2014/images/formula-people.png" /> </span> </div><h5><a target="_blank" href="#"> What you can do in your own operating room Lounge site </a></h5><p>Members can share experiences; post OR notices and documents, make announcements, create working documents, make friends, discuss, collaborate, learn, look for products and services and communicate in the OR in real time. </p></div>
<div class="dt-sc-ico-content  type3"><div class="icon"> <span class="fa fa-ambulance"> <img src="/sites/all/themes/orlounge2014/images/formula-puzzle.png" /></span> </div><h5><a target="_blank" href="#"> How the site will benefit you and your OR </a></h5><p>You will improve your personal professional productivity, increase operating room efficiency and patient safety; upgrade your skills; make friends, enhance your personal and professional lives, and …much more.</p></div>
<div class="dt-sc-ico-content  type3"><div class="icon"> <span class="fa fa-medkit"><img src="/sites/all/themes/orlounge2014/images/formula-speech.png" /> </span> </div><h5><a target="_blank" href="#"> Join people with same interest </a></h5><p>Registered members can further create Special Interest “Lounges” where they meet and collaborate with other members other operating rooms with the same specialty or interest. The Special Interest Lounges could be for Surgical specialties, OR administration, Residency, Teaching, Research, and …much more.</p></div>';
  
 return $output; 
}
function block_home_faq_content(){

   $output = '<div class="home_content">
<div class="col"><div class="title">Professional of the operating room</div><div class="desc">For the first time, people working in the OR can work as a group and align their interests. An Operating Room Lounge site is a management and productivity tool, and a real time messaging site. </div><div class="link"><a href="#">Learn more</a></div></div><div class="col"><div class="title">Orlounge is free to use </div><div class="desc">The sites are administered locally. Each Operating room is responsible for its security and privacy. </div><div class="link"><a href="#">Learn more</a></div></div><div class="col"><div class="title">Need Help ?</div><div class="desc">Surgical professionals with same interest can come together with online tools to work together.</div><div class="link"><a href="#">Learn more</a></div></div>
</div>';
  
 return $output; 
}


function block_register_form($form, &$form_state){
  $form['department'] = array(
	'#type'=>'select',
	'#options'=>array(
			'Physician'=>'Physician',
			'Nurse'=>'Nurse',
			'Resident/fellow'=>'Resident/fellow',
			'Chief of Surgery'=>'Chief of Surgery',
			'OR Manager'=>'OR Manager'
			),

   );
  $form['speciality'] = array(
	'#type'=>'select',
	'#options'=>array(
			   'default'=>'Please Select Speciality',
			   'General Surgery'=>'General Surgery',
			   'Plastic Surgery'=>'Plastic Surgery',
			   'Urology'=>'Urology',
			   'Neurosurgery'=>'Neurosurgery',
			   'Otolarygology'=>'Otolarygology',
			   'Ophthamology'=>'Ophthamology',
			   'Orthopaedic Surgery'=>'Orthopaedic Surgery',
			   'Thoracic Surgery'=>'Thoracic Surgery',
			   'Cardiovascular Surgery'=>'Cardiovascular Surgery',
			   'Paediatric Surgery'=>'Paediatric Surgery',
			   'Obstetrics'=>'Obstetrics',
			   'Gynaecology'=>'Gynaecology',
			   'Craniomaxillaryfacial Surgery'=>'Craniomaxillaryfacial Surgery'				
			 ),
 	'#default_value'=>'default',
  );

  $form['firstname'] = array(
	'#type'=>'textfield',
	'#maxlength'=>30,
	'#size'=>30,
	'#default_value'=>'Your First Name (required)',
  );
  $form['lastname'] = array(
	'#type'=>'textfield',
	'#maxlength'=>30,
	'#size'=>30,
	'#default_value'=>'Your Last Name',
  );
  $form['email'] = array(
	'#type'=>'textfield',
	'#maxlength'=>30,
	'#size'=>30,
	'#default_value'=>'Your Email (required)',
  );
  $form['password'] = array(
	'#type'=>'password',
	'#maxlength'=>30,
	'#size'=>30,
	'#required'=>true,
	'#description'=>t('Your password'),
  );
  $form['password_confirm'] = array(
	'#type'=>'password',
	'#maxlength'=>30,
	'#size'=>30,

	'#description'=>t('Password confirm'),
  );
$form['my_captcha_element'] = array(
  '#type' => 'captcha',
  '#captcha_type' => 'captcha/Math',
);

  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
	'#type'=>'submit',
	'#value'=>t('Next'),	
	
  ); 

  return $form ;
}

function block_register_form_validate($form, &$form_state){

    $password = $form_state['values']['password'];
    $pass_confirm = $form_state['values']['password_confirm'];
    $firstname = $form_state['values']['firstname'];
    $mail =  $form_state['values']['email'];
     if($password!=$pass_confirm){
      form_set_error('password_confirm', t('Passwords do not match.'));
    }
    if(strlen($password)<6){
      form_set_error('password', t('Password length must not be less than 6 characters.'));
    }
    if($firstname=='') {
      form_set_error('firstname', t('First name not is empty.'));
    }
    if(valid_email_address($mail) == 0) {
      form_set_error('email', t('Not a valid email address.'));
    }  
}
function block_register_form_submit($form, &$form_state){

  $mail = $form_state['values']['email'];
  $firstname = $form_state['values']['firstname'];
  $pass = $form_state['values']['password_confirm'];
  register_user_form_data($mail,$firstname,$pass,$form_state);

}

/**
* Create a new user  
*/
function register_user_form_data($mail, $firstname,$pass,&$form_state){

       $check_email = db_query('select count(*) from {users} where mail = :mail', array(
            ':mail' => $mail
        ))->fetchfield();
       $check_name = db_query('select count(*) from {users} where name = :name', array(
            ':name' => $firstname
      ))->fetchfield();
	if($check_email==0){
		if($check_name==0){

                 if($form_state['values']['department']=='OR Manager'){
                   $role = array('5'=>true);
                 } else{
                   $role = array('2'=>true);
                 } 
                $account = array(
                    'name' => $firstname,
                    'pass' => $pass,
                    'mail' => $mail,
                    'status' => 1,
                    'init' => $mail,
                    'roles' => $role
                );
                user_save(null, $account);
		$userRecord = user_authenticate($firstname, $pass);
		$form_state['uid'] = $userRecord;
		user_login_submit(array(), $form_state); 		

		  if($form_state['values']['department']=='OR Manager'){

                     $form_state['redirect'] = 'create/'.$firstname.'/group';  
                  }else{
                     $form_state['redirect'] = 'join/'.$firstname.'/group'; 
                  }
		}else{
		$firstname = $firstname.'1';
		register_user_form_data($mail, $firstname,$pass,$form_state);
		}
	}else{
            drupal_set_message(t('The email '.$mail.' is already taken.'),'error');
	}

}

function registration_welcome(){
    $content = '';
    return theme('welcome',array('content'=>$content));
}

function ORLounge_theme(){
    $item = array(
     'welcome'=>array(  
      'template' => 'welcome',
      'variables' => array('content' => null),
      'path' => drupal_get_path('module', 'ORLounge'),
      ),
    );
return $item;
}


function add_new_comment(){ 
 $nid = $_POST['nid'];
 $uid = $_POST['uid'];
 $comment_body = empty($_POST['comment'])?'':$_POST['comment'];
 $user = user_load($uid);
$comment = new stdClass();

$comment->nid = $nid; // nid of a node you want to attach a comment to
$comment->cid = 0; // leave it as is
$comment->pid = 0; // parent comment id, 0 if none 
$comment->uid = $uid; // user's id, who left the comment
$comment->mail = $user->mail; // user's email
$comment->name = $user->name; // If user is authenticated you can omit this field, it will be auto-populated, if the user is anonymous and you want to name him somehow, input his name here
$comment->thread = '01/'; // OPTIONAL. If you need comments to be threaded you can fill this value. Otherwise omit it.
$comment->hostname = '127.0.0.1' ;// OPTIONAL. You can log poster's ip here
$comment->created = time(); // OPTIONAL. You can set any time you want here. Useful for backdated comments creation.
$comment->is_anonymous = 0; // leave it as is
$comment->homepage = ''; // you can add homepage URL here
$comment->status = COMMENT_PUBLISHED; // We auto-publish this comment
$comment->language = LANGUAGE_NONE; // The same as for a node
$comment->subject = 'Post comment'; 
$comment->comment_body[$comment->language][0]['value'] = $comment_body; // Everything here is pretty much like with a node
$comment->comment_body[$comment->language][0]['format'] = 'filtered_html'; 
//$comment->field_custom_field_name[LANGUAGE_NONE][0]['value'] = 'Some value'; // OPTIONAL. If your comment has a custom field attached it can added as simple as this // preparing a comment for a save

comment_submit($comment); // saving a comment
comment_save($comment);
 

      if($user->picture == null){
       $user_picture_path = '/sites/default/files/styles/50x50/public/pictures/picture-default.jpg';
      }elseif($user->picture==0){
       $user_picture_path = '/sites/default/files/styles/50x50/public/pictures/picture-default.jpg';
      }else{
            $filename = db_query('SELECT filename FROM {file_managed} where fid='.$user->picture)->fetchfield();
       $user_picture_path = '/sites/default/files/pictures/'.$filename;
      }

 print '<div class="comment-row"><img src="'.$user_picture_path.'"><div class="comment-body"><span class="user-name">'.$user->name.'</span>'.$comment_body.'<div class="comment-date">'.format_interval((time() - $comment->created), 2) . t(' ago').'</div></div></div>';
}
/**
 * Implements hook_init().
 */
function ORLounge_init() {
  if (drupal_is_cli() || drupal_installation_attempted()) {
    return;
  }
  // Don't run when site is in maintenance mode
  if (variable_get('maintenance_mode', 0)) {
    return;
  }
  // Ignore non index.php requests (like cron)
  if (!empty($_SERVER['SCRIPT_FILENAME']) && realpath(DRUPAL_ROOT . '/index.php') != realpath($_SERVER['SCRIPT_FILENAME'])) {
    return;
  }

  global $user;

  // let administrator know that there is a config error.
  if (variable_get('site_frontpage', '') == 'front_page' && user_access('administer menu')) {
    drupal_set_message(t('There is a configuration error. The home page should not be set to the path "front_page". Please change this !link', array('!link' => l(t('here'), 'admin/config/system/site-information'))), 'error');
  }

    $join = db_query("select count(*) from {og_membership} where entity_type = 'user' and group_type ='node' and state = 1 and etid =".$user->uid)->fetchfield();

        $arr = array(); 
	$roles = db_query('select rid from {users_roles} where uid = '.$user->uid);
		foreach($roles as $role){
		  $arr[] = $role->rid;		
		}

  if (drupal_is_front_page()){
	if($user->uid==0){
           return ;
        }else if(in_array(4,$arr)){
           return;
        }else if($join==1){
 $gid = db_query("select gid from {og_membership} where entity_type = 'user' and group_type ='node' and state = 1 and etid =".$user->uid)->fetchfield();
        drupal_goto('node/'.$gid);
        }else if($join>1){
          drupal_goto('group_list');
        }else{
          drupal_goto('welcome');
        }	   
  }
}


function group_list_form(){

     global $user;

    $output  = '';
        $arr = array(); 
	$roles = db_query('select rid from {users_roles} where uid = '.$user->uid);
		foreach($roles as $role){
		  $arr[] = $role->rid;		
		}
    if(in_array(4,$arr)){
     $group_arr = db_query("select nid from {node} where type ='group' and  status = 1");
	foreach($group_arr as $group){
              $node = node_load($group->nid);
              if(!empty($node->field_group_logo['und'][0]['filename'])){
                $images = '<div class="field-image"><img src="/sites/default/files/'.$node->field_group_logo['und'][0]['filename'].' "/></div>';
              }else{
                $images = '';
              }

       $query = db_query("select etid from {og_membership} where entity_type ='node' and group_type ='node' and state = 1  and gid =".$group->nid." order by id desc LIMIT 0 , 1")->fetchAssoc();
       if($query!=null){    
           $post = node_load($query['etid']);
            if($post->picture == 0){
              $picture  = '<img width="50" height="50" src="sites/default/files/styles/50x50/public/pictures/picture-default.jpg" />';
            }else{
              $img = db_query('SELECT filename FROM {file_managed} where fid='.$post->picture)->fetchfield();
              $picture = '<img width="50" height="50"  src="/sites/default/files/pictures/'.$img.'">';
            }
           $num = db_query('select count (distinct nid) from {comment} where nid =:nid',array(':nid'=>$post->nid))->fetchfield();

 $comment_body = db_query('select comment_body_value,entity_id from {field_data_comment_body} where entity_id in (select cid from {comment} where nid = :nid)',array(':nid'=>$post->nid));
 $c_output = '';

    foreach($comment_body as $value){
    
    $comments = db_query('select uid,created from {comment} where cid = :cid ', array(':cid'=>$value->entity_id))->fetchAssoc();

      $account = user_load($comments['uid']);
     
      
      if($account->picture == null){
       $user_picture_path = '/sites/default/files/styles/50x50/public/pictures/picture-default.jpg';
      }elseif($account->picture->fid ==0){
       $user_picture_path = '/sites/default/files/styles/50x50/public/pictures/picture-default.jpg';
      }else{
            $filename = db_query('SELECT filename FROM {file_managed} where fid='.$account->picture->fid)->fetchfield();
       $user_picture_path = '/sites/default/files/pictures/'.$filename;
      }
      $c_output .= '<div class="comment-row"><img src="'.$user_picture_path.'" /><div class="comment-body"><span class="user-name">'.$account->name.'</span>'.$value->comment_body_value.'<div class="comment-date">'.format_interval((time() - $comments['created']) , 2) . t(' ago') .'</div></div></div>';
    } 

       if($user->picture ==0){
      $default_picture_path = '/sites/default/files/styles/50x50/public/pictures/picture-default.jpg';
       }else{
            $filename = db_query('SELECT filename FROM {file_managed} where fid='.$user->picture)->fetchfield();
            $default_picture_path = '/sites/default/files/pictures/'.$filename;
       }

           $p_output = '<div id="node-'.$post->nid.'" class="post-content">
  <div class="content">
    <div class="user-picture"><a class="user-picture"  href="/users/shi-zl">'.$picture.'</a></div>
    <div class="user-name">'.$post->name.'</div>
    <div class="post-body">'.$post->body['und'][0]['value'].'</div>
    <div class="post-created">'.format_interval((time() - $post->created) , 2) . t(' ago').'<span class="count_comment"> 
    '.$num.' people comment on this post </span></div>
  </div>
  <div class="post-comment">
               '.$c_output.'
            <div class="form-textarea-wrapper">
	 <img src="'.$default_picture_path.'">   <input type="textarea" onkeydown="enterIn(event,'.$post->nid.','.$user->uid.');" value="Write a comment..." class="add-comment-body comment-node-'.$post->nid.'" cols="60" row="3">
   </div>
       </div>

</div>';
       }else{
        $p_output = '';

       }
	      $output .=  '<div class="custom-view-rows"><div class="field-title"><a href="/node/'.$node->nid.'">'.$node->title.'</a></div>'.$images.'<div class="field-body">'.$node->body['und'][0]['value'].'</div>'.$p_output.'</div>'; 	
	} 
     }else{
    $group_arr = db_query("select gid from {og_membership} where entity_type = 'user' and group_type ='node' and state = 1 and etid =".$user->uid);
          foreach($group_arr as $group){
               $node= node_load($group->gid);

 if(!empty($node->field_group_logo['und'][0]['filename'])){
                $images = '<div class="field-image"><img src="/sites/default/files/'.$node->field_group_logo['und'][0]['filename'].' "/></div>';
              }else{
                $images = '';
              }

       $query = db_query("select etid from {og_membership} where entity_type ='node' and group_type ='node' and state = 1  and gid =".$group->gid." order by id desc LIMIT 0 , 1")->fetchAssoc();
       if($query!=null){    
           $post = node_load($query['etid']);
            if($post->picture == 0){
              $picture  = '<img width="50" height="50" src="sites/default/files/styles/50x50/public/pictures/picture-default.jpg" />';
            }else{
              $img = db_query('SELECT filename FROM {file_managed} where fid='.$post->picture)->fetchfield();
              $picture = '<img width="50" height="50"  src="/sites/default/files/pictures/'.$img.'">';
            }
           $num = db_query('select count (distinct nid) from {comment} where nid =:nid',array(':nid'=>$post->nid))->fetchfield();

 $comment_body = db_query('select comment_body_value,entity_id from {field_data_comment_body} where entity_id in (select cid from {comment} where nid = :nid)',array(':nid'=>$post->nid));
 $c_output = '';

  foreach($comment_body as $value){
    
    $comments = db_query('select uid,created from {comment} where cid = :cid ', array(':cid'=>$value->entity_id))->fetchAssoc();

      $account = user_load($comments['uid']);
      if($account->picture == null){
       $user_picture_path = '/sites/default/files/styles/50x50/public/pictures/picture-default.jpg';
      }elseif($account->picture->fid ==0){
       $user_picture_path = '/sites/default/files/styles/50x50/public/pictures/picture-default.jpg';
      }else{
            $filename = db_query('SELECT filename FROM {file_managed} where fid='.$account->picture->fid)->fetchfield();
       $user_picture_path = '/sites/default/files/pictures/'.$filename;
      }
      
      $c_output .= '<div class="comment-row"><img src="'.$user_picture_path.'" /><div class="comment-body"><span class="user-name">'.$account->name.'</span>'.$value->comment_body_value.'<div class="comment-date">'.format_interval((time() - $comments['created']) , 2) . t(' ago') .'</div></div></div>';
  } 
  if($user->picture ==0){
      $default_picture_path = '/sites/default/files/styles/50x50/public/pictures/picture-default.jpg';
  }else{
            $filename = db_query('SELECT filename FROM {file_managed} where fid='.$user->picture)->fetchfield();
            $default_picture_path = '/sites/default/files/pictures/'.$filename;
  }

          $p_output = '<div id="node-'.$post->nid.'" class="post-content">
  <div class="content">
    <div class="user-picture"><a class="user-picture"  href="/users/shi-zl">'.$picture.'</a></div>
    <div class="user-name">'.$post->name.'</div>
    <div class="post-body">'.$post->body['und'][0]['value'].'</div>
    <div class="post-created">'.format_interval((time() - $post->created) , 2) . t(' ago').'<span class="count_comment"> 
    '.$num.' people comment on this post </span></div>
  </div>
  <div class="post-comment">
               '.$c_output.'
            <div class="form-textarea-wrapper">
	 <img src="'.$default_picture_path.'">   <input type="textarea" onkeydown="enterIn(event,'.$post->nid.','.$user->uid.');" value="Write a comment..." class="add-comment-body comment-node-'.$post->nid.'" cols="60" row="3">
   </div>
       </div>

</div>';
       }else{
        $p_output = '';

       }
	       $output .=  '<div class="custom-view-rows"><div class="field-title"><a href="/node/'.$node->nid.'">'.$node->title.'</a></div>'.$images.'<div class="field-body">'.$node->body['und'][0]['value'].'</div>'.$p_output.'</div>'; 
          }
     } 
  $build['header'] = array(
    '#prefix' => '<div class="view-header">',
    '#suffix' => '</div>', 
  );
  $build['header']['view-header'] = drupal_get_form('override_commons_post_node_form');
  $build['view-content'] = array(
    '#markup' => '<div class="view-content">'.$output.'</div>',
  );

 return $build;
}



function override_commons_post_node_form($form,&$form_state){
 
   global $user;
    $options = array();
 
        $arr = array(); 
	$roles = db_query('select rid from {users_roles} where uid = '.$user->uid);
		foreach($roles as $role){
		  $arr[] = $role->rid;		
		}
    if(in_array(4,$arr)){
     $group_arr = db_query("select nid ,title from {node} where type ='group' and  status = 1");
	foreach($group_arr as $group){
	   $options[$group->nid] = $group->title; 	
	} 
     }else{
    $group_arr = db_query("select gid from {og_membership} where entity_type = 'user' and group_type ='node' and state = 1 and etid =".$user->uid);
          foreach($group_arr as $group){
		 $group_title = db_query("select title from {node} where type ='group' and nid =".$group->gid)->fetchfield();
		$options[$group->gid] = $group_title;
          }
     } 

   $form['body'] = array(
     '#type'=>'textarea',
     '#default_value'=>t("What's on your mind?"),
    ); 
   $form['og_group_ref']=array(
     '#type' => 'select',
     '#options' => $options,
    );
   $form['actions'] = array('#type'=>'actions');
   $form['actions']['submit'] = array(
      '#type'=>'submit',
      '#value'=>t('post'),
    );  
  
   return $form;
}


function override_commons_post_node_form_validate(&$form,&$form_state){
 
 if($form_state['values']['body']==null || $form_state['values']['body']=="What's on your mind?"){
    form_set_error('body','body is required.');
 }

}
function override_commons_post_node_form_submit(&$form,&$form_state){

  if(strlen($form_state['values']['body'])>20){
    $title = substr($form_state['values']['body'],0,20);
  }else{
    $title = $form_state['values']['body'];
  } 
 global  $user;
$newNode = (object) NULL; 
   $newNode->type = 'post'; 
   $newNode->uid = $user->uid; 
   $newNode->title = $title;
   $newNode->created = strtotime("now");
   $newNode->changed = strtotime("now");
   $newNode->status = 1; 
   $newNode->comment = 0; 
   $newNode->promote = 0; 
   $newNode->sticky = 0; 
   $newNode->tnid = 0; 
   $newNode->language = 'und';
   if($form_state['values']['body']!=null){
      $newNode->body[$newNode->language][0]['value'] = $form_state['values']['body'];
   }else{
   $newNode->body[$newNode->language][0]['value'] ='';
   }
   $newNode->body[$newNode->language][0]['summary'] = '';
   $newNode->body[$newNode->language][0]['format'] = 'filtered_html'; 


  node_object_prepare($newNode);
  // Save the node.  // The node will also get published, if $newNode->status was set to 1. 
   $node = node_submit($newNode);
   node_save($node);   
   $nid = db_query("select nid from {node} where type = 'post' order by nid desc LIMIT 0 , 1")->fetchfield();
   db_insert('og_membership') // Table name no longer needs {}
     ->fields(array(
    'type' => 'og_membership_type_default',
    'etid' => $nid,
    'entity_type' => 'node',
    'gid' =>$form_state['values']['og_group_ref'],
    'group_type'=>'node',
    'state'=> 2,
    'created'=>strtotime("now"),
    'field_name'=>'og_group_ref',
    'language'=>'en',  
  ))
  ->execute();
drupal_set_message(t('Post '.$title.' has been created.'));

}

